### ISSUE TITLE
No level.destroy() ? 

### ISSUE THREAD

**Issue by eslachance** [substack/level-party#15]
Hi guys,

Sorry to be a bother. I have a little `native-level-promise` module that works great with `level` itself, but when I try to use `level-party` as a drop-in replacement, it complains about `level.destroy()` not being a function.  You can see the code here: 
https://github.com/eslachance/native-level-promise/blob/master/index.js

Error on line 19, when using `level-party` instead of just `level`.

I am unfortunately not talented enough to really understand your code, and would greatly appreciate the assist on this one. 

Gratzie,
Evie

**Comment by ralphtheninja** [comment]
After a quick glance it seems https://github.com/mafintosh/multileveldown/blob/master/leveldown.js is used as a backend to `levelup`, but it doesn't have destroy functionality. `level` however has since it bundles `leveldown` (destroy is set by `level-packager` here https://github.com/Level/packager/blob/master/level-packager.js#L14-L20)

**Comment by eslachance** [comment]
But `level-party` depends on `level` which does return the destroy() and repair() methods, so shouldn't this work?

**Comment by ralphtheninja** [comment]
Yes, it depends on `level`, but doesn't return one. Instead it returns `multileveldown.client()` https://github.com/substack/level-party/blob/master/index.js#L17

**Comment by eslachance** [comment]
Is there any workaround to this issue I'm presenting, any way to access destroy() and repair()?

**Comment by ralphtheninja** [comment]
One workaround could be to not add any wrappers if `.destroy()` or `.repair()` doesn't exist

**Comment by eslachance** [comment]
You're frustratingly unhelpful right now.

**Comment by ralphtheninja** [comment]
> You're frustratingly unhelpful right now.

How can I be more helpful?

**Comment by eslachance** [comment]
The reason .destroy() exists, is to completely remove all traces of the level database, by deleting the files. Which obviously in a multilevel environment might be an issue, and yet, is still something one might want to do. So, what would be the option here? Is there a way to destroy a database, and if so, how? 

The reason .repair() exists, is to attempt to fix a corrupted level database. Is still still relevant? If so, how would one repair a database if that method isn't there. If not, what prevents the database from being corrupted in a multilevel environment?

**Comment by ralphtheninja** [comment]
You're asking frustratingly many questions :grinning: 

You could submit a pull request to `multileveldown` that adds `.destroy()` and `.repair()` functionality.

**Comment by eslachance** [comment]
In the word of a famously wise woman who changed the world with her enlightenment: 

```
Ain't nobody got time fo dat!
```
