### ISSUE TITLE
Why level-prebuilt?

### ISSUE THREAD

**Issue by binarykitchen** [substack/level-party#7]
If leveldown (>= 1.2.2) now supports prebuilds, we probably shouldn't be using the fork ` level-prebuilt` anymore (it causes node-gyp.js troubles under iojs anyway)

**Comment by mafintosh** [comment]
yep we should just change this back to leveldown now

**Comment by binarykitchen** [comment]
@mafintosh can you do that now? because I think it is breaking something on my server and it's probably related to https://github.com/mafintosh/leveldown-prebuilt/issues/7

**Comment by mafintosh** [comment]
I was offline camping in Sweden. Fixed in 2.1.2

**Comment by mafintosh** [comment]
@binarykitchen also if you run into this problem with other modules you can use https://github.com/mafintosh/node-gyp-install to fix node-gyp under iojs

**Comment by binarykitchen** [comment]
Thanks, v1.2.1 worked like a charm and node-gyp-install isn't needed at all..
Unfortunately there is a new error ... will open a new issue.
